### PR TITLE
fix build for ios/darwin

### PR DESCRIPTION
**Pull request by timwr**
This PR fixes libsigar to work on iOS.
I might need to revisit this later, but at least for now it builds and works.

I'm doing things like: include "if_types.h"
I could have simply returned SIGAR_ENOTIMPL for these functions, not sure which is better.

### CODE REVIEW

**Comment by busterb** [comment]
This looks good enough go get us over the initial humps. Thanks!

**Comment by busterb** [comment]
We could probably go spelunking through some of the other sigar forks for more iOS bits as well. I found an Android fork a while back that I extracted some fixes from.

**Comment by busterb** [comment]
I rebased and squashed (since this itself is a fork of a fork) see ed51a454 - I'll start pushing these changes back to the boundary fork shortly. Thanks!

**Comment by timwr** [comment]
Awesome thanks @busterb

**Pull request closed without merging**
